FROM spotify/kafka:latest

# This file is mostly to get a consistent container name
# so the create-topic.sh file doesn't have to be edited w/ the
# container id

ENV ADVERTISED_HOST 192.168.99.100
ENV ADVERTISED_PORT 9092